name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v2.1.0
        with:
          style: file
          sources: "
            engine/**/*.hpp,
            engine/**/*.cpp,
            editor/**/*.hpp,
            editor/**/*.cpp,
            application/**/*.hpp,
            application/**/*.cpp"